### ISSUE TITLE
Change backend directory structure naming from 'source' to 'directory'

### ISSUE THREAD

**Issue by Evan-Leon** [mediacloud/web-search#217]
- This is an effort to help the slightly confusing naming we have in mcweb.
- This will involve numerous changes all across the app:
  - Django:
    - settings.py
    - urls.py
    - 'sources'  -> 'directory'
    - ensure all imports are correct
  - RTK/Frontend:
    - will need to adjust api calls in sourceApi.js

* keep api/sources routes until rss fetcher is able to adjust its api calls (refer to phil's comment below)

**Comment by philbudne** [comment]
request: if you plan to rename /api/sources to /api/directory, please consider briefly having both available (two path lines in urls.py), so that rss-fetcher doesn't have to make the change at the exact same time!
