### ISSUE TITLE
Bug with manually typing dates into datepicker

### ISSUE THREAD

**Issue by Evan-Leon** [mediacloud/web-search#315]
When attempting to type dates manually into datepicker it tends to auto correct immediately to like 2002. 
Here is a l[ink](https://github.com/mui/mui-x/issues/6232) that notes that this seems to be a problem, I didn't have a chance to read too much more but looks like they may have a solution.

**Comment by evansuslovich** [comment]
Once there is a change to an input, the information is dispatched to the store regardless of validation. However, the date values are set to the startDate and endDate and those values are pulled from the state. We need a temporary variable in between inputting to dispatching that validates this. DayJS is quite unreliable to validate dates so I might have to play around in the utils folder and create some helper functions. 

User inputs a date that isn't valid (01/01/200) -> Dispatch to state -> DatePicker's value is pulled from the State despite validity. 

Solution: Create validation in between the user inputting a date and dispatching to the store.
