### ISSUE TITLE
'Last Month' and 'Last 3 Months' Buttons not functioning

### ISSUE THREAD

**Issue by evansuslovich** [mediacloud/web-search#350]
Cannot set properties of undefined (setting 'undefined')

**Comment by ThienBNguyen** [comment]
hi can i work in the issue

**Comment by evansuslovich** [comment]
> hi can i work in the issue

Yes! email me at suslovich.e@northeastern.edu

**Comment by ThienBNguyen** [comment]
I am sorry to say this. I have take a look at the codebase it is out of my expertise
