### ISSUE TITLE
Throttle twitter to try and reduce 429 errors

### ISSUE THREAD

**Issue by Evan-Leon** [mediacloud/web-search#359]
We often get a 429 error when querying Twitter. This is likely due to many requests at the same time. 
We should attempt to throttle our requests to twitter to try and ensure we are politely requesting the information and not getting 429s.

**Comment by evansuslovich** [comment]
Is Twitter API shutting down ... if not, can we use a background task?

**Comment by Evan-Leon** [comment]
pricing does seem like it is going to be prohibitive for most people (100/mo for most basic tier to be able to read) (free package looks to only be for write access).
may be able to fix the 429 by making sure all results queries are not sent at the same time. Could add a delay which I think background tasks would essentially be doing, but maybe could be done with just a small timeout instead if the query is from twitter (?)
