### ISSUE TITLE
error when trying to search online news

### ISSUE THREAD

**Issue by SheryarKhaliq125** [mediacloud/web-search#483]
You've closed my issue without providing a solution: https://github.com/mediacloud/web-search/issues/482

I've added the following lines to the mcweb/.env 

MEDIA_CLOUD_API_KEY=4a6e7196b5fb0ed06d55e5ef62f9b94f382b01a5
MEDIA_CLOUD_API_URL=https://search.mediacloud.org/

But still it shows the same error, you can also check it from here: https://media.eventassay.com/search

![image](https://github.com/mediacloud/web-search/assets/105570808/a858fd6e-1ab0-4925-9916-6d15bfe0cc6e)
![image](https://github.com/mediacloud/web-search/assets/105570808/996ed468-929a-41ad-9965-d5d251e1e610)

**Comment by Evan-Leon** [comment]
Hello, my apologies for the confusion. I do not believe your use case will work without a Legacy Media Cloud API key (issued pre 8/22). The current api key that is found in your profile does not work with the Media Cloud Legacy API. We no longer have access to the previous system to generate Legacy Media Cloud API keys. Essentially, if you did not have an api key for the Media Cloud Legacy system, over a year ago, then you will not be able to query Media Cloud Legacy locally.

Any searches you would like to make through the Media Cloud Legacy API should be able to be made through the current live application, found at search.mediacloud.org.

But if you would like to follow up with me via email e.leon@northeastern.edu, I would be happy to help and discuss further.
