### ISSUE TITLE
No collections are showing

### ISSUE THREAD

**Issue by SheryarKhaliq125** [mediacloud/web-search#484]
Sir i cannot able to see the Featured or collections or any collections at all. No sources available.

I've following questions:

1) How to importdata : i already data didn't tried manage.py importdata it didn't help
2) How to connect media cloud with other sources such as: https://www.thepacker.com/ , https://www.fmi.org/

![Screenshot from 2023-08-16 15-56-53](https://github.com/mediacloud/web-search/assets/105570808/edb53070-3e0a-4f71-9dd4-019c44181f26)
![Screenshot from 2023-08-16 15-56-48](https://github.com/mediacloud/web-search/assets/105570808/d91e875c-a6a9-449d-a369-97e5310a444c)
![Screenshot from 2023-08-16 15-56-05](https://github.com/mediacloud/web-search/assets/105570808/ac1720b9-56f1-40e0-a260-957f7c2b54b6)

**Comment by Evan-Leon** [comment]
Hello, if you would like to reach out via email to e.leon@northeastern.edu, it may be a little easier to troubleshoot this.
