### ISSUE TITLE
Optimizing Alert System

### ISSUE THREAD

**Issue by evansuslovich** [mediacloud/web-search#494]
Currently runs on a single worker that blocks any incoming requests for that worker (ex. large downloads), large downloads will still work, but after alert system runs. 
Currently low priority because everything still works, just a delay.

**Comment by pgulley** [comment]
I think maybe we should think about this ultimately being something we run in prefect- i don't think it makes sense to run on the web search image, since it is blocking.

**Comment by Evan-Leon** [comment]
New source health app in development
