### ISSUE TITLE
Create three worker queues

### ISSUE THREAD

**Issue by Evan-Leon** [mediacloud/web-search#760]
Create THREE (refer to Phil's comments) different queues for workers/django background tasks, one for short term tasks (large downloads) and an additional queue for longer running tasks (alert system).

**Comment by Evan-Leon** [comment]
Notes from Phil:
- This requires adding queue="queue-name" argument to the @background() decorator call
- AND a line starting a worker for the named queue in the Dokku Procfile

**Comment by philbudne** [comment]
My suggestion was three queues:

One for system tasks, one for short running user tasks (rescrape source),
and one for longer user tasks (rescrape collection, possibly "crawl source
for all sitemaps")

**Comment by philbudne** [comment]
The current flavors of background tasks:
1. email zipped csv of query results to user (could take 15 minutes)
2. rescrape a single source for user (quick, but may hang)
3. rescrape an entire collection (slow, often hangs, work in progress)
4. alert system (system task)
5. update story counts (system task)

An additional flavor is "crawl an entire site for sitemaps generate an email to be perused by a human"

NOTE: The django background task facility doesn't allow for multiple workers on a queue, there can be multiple queues (only requires adding a worker process in Procfile), but queue per task flavor would probably be a mistake if the number of tasks grows large.

So maybe six queues:
{ system, admin, user } x { fast, slow }

system-fast: update story counts?

**Comment by philbudne** [comment]
Also: the two "system tasks" could also be done:
1. via regular crontab entries performing "dokku run" or "dokku enter" commands
2. dokku/cron integration: https://dokku.com/docs/processes/scheduled-cron-tasks/

**Comment by Evan-Leon** [comment]
I think that all sounds reasonable and I think six queues should suffice for current slate of background tasks.
Additionally just queued up an issue for dokku/cron integration 🙏 
Thank you for the work 🧙

**Comment by philbudne** [comment]
Just trying to help nudge the ball down the field!  I added a manage.py command to run scrape collection from the command line to try and find problems since it had just hung, and blocked the CSV emails, it was very much in my mind, and I was thinking I'd just add the queues, and realized it was more complicated than I originally thought!

**Comment by pgulley** [comment]
I'm definitely in favor of adding more worker queues. I've been wondering though, as we add new background processes, if having them all live within the django stack is the best course of action, when we also have the prefect worker queue on guerin and could grow or shrink that without changes in the web-search codebase. I'd love a compare/contrast of the two approaches because I'm sure there's cases for both sides.

**Comment by philbudne** [comment]
Different aspects for evaluation:
good for regular tasks?
closely tied to mcweb PG db?
user visible (and cancelable?)?
negative impacts on interactive users?
needs to controllable by web site admin?
expected timeliness?
critical/core function for web site use?
able to set max run time?
allows exclusion (or replacement) of existing tasks?

Available technologies w/ strengths and weaknesses:
cron: good for regular tasks without user visibility; does not provide max time, exclusion
django background_task: provides visibility, replacement; no time limit, can only run one worker per queue (not super complicated/flexible)
sous-chef/prefect: @pgulley ?

The existing background tasks:
1. Update source stories/week (using rss-fetcher API)
      a cron job that does "docker exec manage.py do-work" seems like a no-brainer to me
2. Source/collection alerts (currently only using rss-fetcher API, but could additionally use ES)
5. Rescrape source
6. Rescrape collection
7. Run query and email Zip'ed CSV of all URLs

**Comment by philbudne** [comment]
Oops hit ctrl-enter!  continuing:

number 2 above: not closely tied to mcweb-db (users list and monitored collections are in config and a JSON file respectively).  If it starts looking at ES, maybe it belong as a prefect job?

number 3 & 4: for admin visibility, and closeness to mcweb-db, I'd vote keep as a django task

number 5:  The single execution queue limitation of django tasks is a feature here (keeps users from DoSing the system)?    Executes the queries against the user's quota, so close to the mcweb-db, but using sous-chef could make more analysis tools available?

My two cents:
In terms of complexity and robustness (only requires django app to provide user services), it's better to keep things inside the django app when the task is simple and needs to be user visible...

**Comment by philbudne** [comment]
I Just realized; using sous-chef as-is for background tasks for
ordinary users would bypass the query quota system, since sous-chef
uses mc-providers to access the ES.

(And I had recently joked that someday someone might want to use
mc-providers, but using the mcweb API instead of the (now built-in)
news-search-api client code for ES access....)

**Comment by philbudne** [comment]
Looking into djange-background-tasks:

It does allow multiple workers:

BACKGROUND_TASK_ASYNC_THREADS defaults to the number of virtual CPU's
available (32 on tarbell).  It *IS* creating a worker pool with 32
threads, but only one task ever runs at a time unless
BACKGROUND_TASK_RUN_ASYNC is set to True, which would allow 32 tasks
to run in parallel.

I don't think running 32 big queries in parallel is something we would
currently want, and given the propensity of the "scrape collection"
task to hang, it could gum up threads one after another, so
segregation of different kinds of work into different queues while
that is worked out is helpful.

Another fun feature: You can set BACKGROUND_TASK_MAX_RUNTIME, but I
don't think that cancels the running task, it looked to me like it may
just change the database row for the task, so it can be launched again
(and possibly jam up another worker thread).

P.S.
I had been working on a branch to implement multiple queues,
and I may have solved the last problem.  Will open a PR
with Evan and Paige as reviewers.
