### ISSUE TITLE
Add new Collections "Contributor" user role

### ISSUE THREAD

**Issue by pgulley** [mediacloud/web-search#769]
To allow for more community members to contribute to our collections, while also preserving the integrity of our long-running collections, we want to add a role with intermediate permissions, and some associated safety flags to collections.

- Add "Static" flag to collections
- If a collection is flagged "Static", no other properties can be edited by anyone
- Only "Staff" users can toggle the 'static' property
- "Contributor" users can edit non-static collections
- "Contributor" users can also edit sources, but will be presented with an error message and additional confirmation steps to reduce likelihood of editing key sources.

**Comment by pgulley** [comment]
I think the consensus right now is that we are going to be going in on using Django Auth's Group Permissions feature, presumably creating a "contributor" group- where belonging to the group has the same effect as possessing a "contributor" flag as above

**Comment by Evan-Leon** [comment]
closed with #824
